image: lofi-girl-relay
build_from:
  amd64: "savonet/liquidsoap-alpine:v2.2.5"
  aarch64: "savonet/liquidsoap-alpine:v2.2.5"
  armv7: "savonet/liquidsoap-alpine:v2.2.5"
args:
  BASHIO_VERSION: 0.16.2
  TEMPIO_VERSION: 2021.09.0
  S6_OVERLAY_VERSION: 3.1.6.2
  JEMALLOC_VERSION: 5.3.0