name: "Liquidsoap"
description: "Liquidsoap runner"
version: "2.2.4-1"
image: "ghcr.io/palakis/hassio-addon-liquidsoap"
slug: liquidsoap
init: false
ports:
  8000/tcp: 8000
ports_descriptions:
  8000/tcp: "Harbor server"
map:
  - addon_config:rw
  - media:rw
arch:
  - amd64