name: "Liquidsoap"
description: "Liquidsoap runner for Home Assistant, bundled with yt-dlp"
version: "2.3.0"
image: "ghcr.io/palakis/hassio-addon/liquidsoap-{arch}"
slug: liquidsoap
init: false
ports:
  8000/tcp: 8000
ports_descriptions:
  8000/tcp: "Harbor server"
schema:
  environment:
    - str
options:
  environment: []
map:
  - addon_config:rw
  - media:rw
  - share:rw
arch:
  - amd64
  - aarch64
# Codenotary is disabled in the supervisor since 2023.4.0, and it's currently (2024.6.4) still
# is the case until the feature gets reworked with cosign.
# Putting this here will just make the addon UI show the "Signed" badge without having to get it signed by Codenotary.
codenotary: stephane.lepin@gmail.com
