name: "Liquidsoap"
description: "Liquidsoap runner for Home Assistant, bundled with yt-dlp"
version: "2.2.4-2"
image: "ghcr.io/palakis/hassio-addon/liquidsoap-{arch}"
slug: liquidsoap
init: false
ports:
  8000/tcp: 8000
ports_descriptions:
  8000/tcp: "Harbor server"
map:
  - addon_config:rw
  - media:rw
  - share:rw
arch:
  - amd64
  - aarch64
  - armv7
