name: 'Continuous integration'

on:
  push:
    branches:
      - main

jobs:
  build_images:
    name: 'Build image'
    strategy:
      matrix:
        arch: [amd64]
        addon: [liquidsoap]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: gchr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on image
        uses: home-assistant/builder@master
        with:
          args: |
            --test \
            --${{ matrix.arch }} \
            --target ${{ matrix.addon }}
