name: 'Publish add-on images'

on:
  push:
    branches:
      - main

jobs:
  build_images:
    name: 'Build image'
    strategy:
      matrix:
        arch: [amd64, aarch64, armv7]
        addon: [liquidsoap]
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build add-on image
        uses: home-assistant/builder@master
        with:
          args: |
            --${{ matrix.arch }} \
            --target ${{ matrix.addon }}
